# Use official Python runtime
FROM python:3.10-slim

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV EXCEL_DB_PATH=/data/GDARD.xlsx

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Ensure /data directory exists and copy Excel DB
RUN mkdir -p /data
COPY app/data/GDARD.xlsx /data/GDARD.xlsx

# Expose port
EXPOSE 5000

# Default command to run the app
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
